# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.14.6
    steps:
      - checkout
      - run:
          name: Run tests and coverage
          command: go test -race -coverprofile=coverage.txt -covermode=atomic
            - run:
                name: Upload coverage to Codecov
                command: bash <(curl -s https://codecov.io/bash)

workflow:
  version: 2.1
  build-test:
    jobs:
      - build