name: CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:

  # The “build” workflow
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: Build
      run: go build -v ./...

    - name: Vet
      run: go vet ./...

    - name: Lint
      run: golint ./...

    - name: Test
      run: go test -v ./...
